import {
  BarChart3,
  Boxes,
  CalendarClock,
  Gift,
  Heart,
  KeyRound,
  LayoutDashboard,
  LifeBuoy,
  MapPin,
  Settings,
  Star,
  Store,
  Table2,
  Tag,
  Truck,
  Users,
  UtensilsCrossed,
  Webhook,
} from "lucide-react";

import type { ModuleKey } from "@/lib/modules/keys";

export const ADMIN_NAV_ITEMS = [
  { href: "/admin", labelKey: "dashboard", icon: LayoutDashboard, exact: true, moduleKey: null },
  { href: "/admin/menu", labelKey: "menu", icon: UtensilsCrossed, exact: false, moduleKey: null },
  { href: "/admin/tables", labelKey: "tables", icon: Table2, exact: false, moduleKey: null },
  { href: "/admin/staff", labelKey: "staff", icon: Users, exact: false, moduleKey: null },
  {
    href: "/admin/reservations",
    labelKey: "reservations",
    icon: CalendarClock,
    exact: false,
    moduleKey: "reservations" satisfies ModuleKey,
  },
  { href: "/admin/ratings", labelKey: "ratings", icon: Star, exact: false, moduleKey: null },
  { href: "/admin/campaigns", labelKey: "campaigns", icon: Tag, exact: false, moduleKey: "campaigns" satisfies ModuleKey },
  { href: "/admin/loyalty", labelKey: "loyalty", icon: Heart, exact: false, moduleKey: "crm_loyalty" satisfies ModuleKey },
  { href: "/admin/gift-cards", labelKey: "giftCards", icon: Gift, exact: false, moduleKey: "gift_cards" satisfies ModuleKey },
  { href: "/admin/ingredients", labelKey: "ingredients", icon: Boxes, exact: false, moduleKey: "inventory" satisfies ModuleKey },
  { href: "/admin/suppliers", labelKey: "suppliers", icon: Truck, exact: false, moduleKey: "inventory" satisfies ModuleKey },
  { href: "/admin/delivery-zones", labelKey: "deliveryZones", icon: MapPin, exact: false, moduleKey: "delivery" satisfies ModuleKey },
  { href: "/admin/api-keys", labelKey: "apiKeys", icon: KeyRound, exact: false, moduleKey: "api_access" satisfies ModuleKey },
  { href: "/admin/webhooks", labelKey: "webhooks", icon: Webhook, exact: false, moduleKey: "api_access" satisfies ModuleKey },
  { href: "/admin/marketplace", labelKey: "marketplace", icon: Store, exact: false, moduleKey: "marketplace" satisfies ModuleKey },
  { href: "/admin/reports", labelKey: "reports", icon: BarChart3, exact: false, moduleKey: null },
  { href: "/admin/support", labelKey: "support", icon: LifeBuoy, exact: false, moduleKey: null },
  { href: "/admin/settings", labelKey: "settings", icon: Settings, exact: false, moduleKey: null },
] as const;
